--- # Cron mod
- hosts: apacheweb
  user: test
  connection: ssh
  gather_facts: no
  tasks: 
  - name: Add a cron job
    cron: name="list files" minute='49' hour='14' job='ls -al > /home/test/cronres.log'
