--- # Outline to Playbook Translation
- hosts: apacheweb
  user: test 
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time stamp for when the playbook starts 
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: Install Apache Web Server
    action: yum name=httpd state=installed
    notify: Restart HTTPD
  
  - name: Verify that the web service is running
    command: systemctl status httpd
    register: result
  - debug: var=result  
  - name: Install client software - telnet
    yum: pkg=telnet state=latest  
  - name: Install client software - elinks
    yum: pkg=elinks state=latest
  - name: log all the packages install on the system
    command: yum list installed 
    register: installed_result
  - debug: var=installed_result
  - name: date/time stamp for when the playbook ends
    command: date
    register: timestamp_ends
  - debug: var=timestamp_ends

  handlers:
  - name: Start HTTPD
    service: name=httpd state=restarted
