--- # Prompt for user pkg ex.
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars: 
    playbook_version: 0.01b
  vars_prompt: 
    - name: pkgtoinstall
      prompt: Install which Package?
      default: telnet
      private: no
  tasks:
  - name: Install the indicated pkg
    yum: pkg={{ pkgtoinstall }} state=latest
    
